<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-U5PV2QM" failures="1" tests="2" name="Error validation" time="15.241" errors="0" timestamp="2024-08-22T12:41:50 EDT">
  <testcase classname="vaibhav.tests.ErrorValidation" name="loginError" time="1.215">
    <skipped/>
  </testcase> <!-- loginError -->
  <testcase classname="vaibhav.tests.ErrorValidation" name="loginError" time="1.331">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at vaibhav.tests.ErrorValidation.loginError(ErrorValidation.java:20)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
... Removed 19 stack frames]]>
    </failure>
  </testcase> <!-- loginError -->
</testsuite> <!-- Error validation -->
